### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by mmaalvarez** [compbiomed-unito/MUSE-XAE#1]
Hi, would MUSE-XAE work in the following scenario?:

1. Number of variables (i.e. rows in the input table) is >96
2. Variables follow a non-Poisson (e.g. normal) distribution
3. Variables have both negative and positive continuous values

Thanks!
Miguel

**Comment by cpancott** [comment]
Hi Miguel,
thanks for your message!
I will answer point by point.

1. MUSE-XAE, in its present form, works only for SBS signatures in the 96 mutational channel format.
We are working on a more thorough version of the tool that it will include also the double strand (192 channels ), the pentanucleotide representation (1536 channels) and others. In addittion it will also include other mutational events, like double base substitutions, Indels and CNV. After that we will certainly release MUSE-XAE as a python package.

2-3. MUSE-XAE takes in input count values and it has some constraint that force the output to be positive.


Best,
Corrado

**Comment by mmaalvarez** [comment]
Thanks a lot for your answer
As for the count values, if I analyzed a different type of data (e.g. effect sizes), while also using another distribution to model the loss (e.g. instead of Poisson, normal), would it still generate meaningful signatures (although of course not the SBS96 COSMIC-like ones)?

**Comment by cpancott** [comment]
Dear Miguel,
the architecture is flexibile and easy adaptable.
If you want to use it with a gaussian loss you can. Probably you have to readapt a bit the code.
The meaning of the decoder depends on your data and what you are looking for.
If you want to discuss it in more detail, i am open to do it.
Write me an email if you want corrado.pancotti@unito.it, so i can close the issue.
Thanks.

Best,
Corrado
